-- Python Dictionary examples

In [2]:
person = {
    "first": "Corey",
    "last": "Schafer",
    "email": "CoreyMSchafer@gmail.com"
}

In [3]:
people = {
    "first": ["Corey"],
    "last": ["Schafer"],
    "email": ["CoreyMSchafer@gmail.com"]
}

In [4]:
people = {
    "first": ["Corey", 'Jane', 'John'],
    "last": ["Schafer", "Doe", "Doe"],
    "email": ["CoreyMSchafer@gmail.com", "JaneDoe@gmail.com", "JohnDoe@gmail.com"]
}

In [5]:
people["email"]
# dataframes are similar to this, but they have more functionality than what we have in standard python dictionaries.

['CoreyMSchafer@gmail.com', 'JaneDoe@gmail.com', 'JohnDoe@gmail.com']

-- Importing pandas library

In [6]:
import pandas as pd

In [7]:
df = pd.DataFrame(people)

In [8]:
df

   first     last                    email
0  Corey  Schafer  CoreyMSchafer@gmail.com
1   Jane      Doe        JaneDoe@gmail.com
2   John      Doe        JohnDoe@gmail.com

In [9]:
df['email']

0    CoreyMSchafer@gmail.com
1          JaneDoe@gmail.com
2          JohnDoe@gmail.com
Name: email, dtype: str

In [10]:
type(df['email'])
# this means that the data type of the column is a pandas series object, which is similar to a list in python.
# a dataframe is basically a container of multiple series objects, where each series object is a column in the dataframe.

pandas.Series

In [11]:
df.email

0    CoreyMSchafer@gmail.com
1          JaneDoe@gmail.com
2          JohnDoe@gmail.com
Name: email, dtype: str

In [12]:
df[['last', 'email']]
# by doing this, we can access multiple columns in a dataframe, and the result will be a new dataframe with only the selected columns.
# it's just like the SQL SELECT statement

      last                    email
0  Schafer  CoreyMSchafer@gmail.com
1      Doe        JaneDoe@gmail.com
2      Doe        JohnDoe@gmail.com

In [13]:
df.columns

Index(['first', 'last', 'email'], dtype='str')

In [14]:
df.iloc[0]
# iloc allows us to access rows by integer location
# here, the indexes become the column names

first                      Corey
last                     Schafer
email    CoreyMSchafer@gmail.com
Name: 0, dtype: str

In [15]:
df.iloc[[0, 1]]
# by doing this, we can access both the first and second rows of the dataframe, and the result will be a new dataframe with only the selected rows.
# be sure to put an inner list inside the brackets

   first     last                    email
0  Corey  Schafer  CoreyMSchafer@gmail.com
1   Jane      Doe        JaneDoe@gmail.com

In [28]:
df.iloc[[0, 1], 2]
# if we think of loc and iloc as functions, the first argument are the rows that we want to select, and the second argument are the columns that we want to select.

0    CoreyMSchafer@gmail.com
1          JaneDoe@gmail.com
Name: email, dtype: str

In [19]:
df

   first     last                    email
0  Corey  Schafer  CoreyMSchafer@gmail.com
1   Jane      Doe        JaneDoe@gmail.com
2   John      Doe        JohnDoe@gmail.com

In [ ]:
df.loc[0]
# with loc we're going to be searching rows by labels

first                      Corey
last                     Schafer
email    CoreyMSchafer@gmail.com
Name: 0, dtype: str

In [24]:
df.loc[[0, 1], 'email']

0    CoreyMSchafer@gmail.com
1          JaneDoe@gmail.com
Name: email, dtype: str

In [29]:
df.loc[[0, 1], ['email', 'last']]

                     email     last
0  CoreyMSchafer@gmail.com  Schafer
1        JaneDoe@gmail.com      Doe