In [ ]:
from google.colab import files
import pandas as pd
import numpy as np
import io

In [ ]:
uploaded = files.upload()

Saving Top 1000 technology companies.csv to Top 1000 technology companies.csv

In [ ]:
file_name = list(uploaded.keys())[0]

In [ ]:
companies_df = pd.read_csv(io.BytesIO(uploaded[file_name]))

In [ ]:
companies_df.head()

,Ranking,Company,MarketCap,Stock,Country,Sector,Industry
0,1,Apple Inc.,$2.866 T,AAPL,United States,Technology,Consumer Electronics
1,2,Microsoft Corporation,$2.755 T,MSFT,United States,Technology,Software—Infrastructure
2,3,Nvidia Corporation,$1.186 T,NVDA,United States,Technology,Semiconductors
3,4,Broadcom Inc.,$495.95 B,AVGO,United States,Technology,Semiconductors
4,5,Taiwan Semiconductor Manufacturing Company Lim...,$487.64 B,2330,Taiwan,Technology,Semiconductors

In [ ]:
companies_df.columns = [x.lower() for x in companies_df.columns]
# deixando os nomes de todas as colunas com letras minúsculas

In [ ]:
companies_df.head()

,ranking,company,marketcap,stock,country,sector,industry
0,1,Apple Inc.,$2.866 T,AAPL,United States,Technology,Consumer Electronics
1,2,Microsoft Corporation,$2.755 T,MSFT,United States,Technology,Software—Infrastructure
2,3,Nvidia Corporation,$1.186 T,NVDA,United States,Technology,Semiconductors
3,4,Broadcom Inc.,$495.95 B,AVGO,United States,Technology,Semiconductors
4,5,Taiwan Semiconductor Manufacturing Company Lim...,$487.64 B,2330,Taiwan,Technology,Semiconductors

In [ ]:
companies_df.shape
# o dataframe tem 1000 linhas e 7 colunas

(1000, 7)

In [ ]:
# encontrar colunas com dados do tipo String ou object
string_columns = companies_df.select_dtypes(include='object').columns

# aplicar .str.lower() para todas colunas com String
companies_df[string_columns] = companies_df[string_columns].apply(lambda x: x.str.lower() if x.dtype == 'object' else x, axis=0)

# mostrar dataframe para ver mudanças
companies_df.head()

,ranking,company,marketcap,stock,country,sector,industry
0,1,apple inc.,$2.866 t,aapl,united states,technology,consumer electronics
1,2,microsoft corporation,$2.755 t,msft,united states,technology,software—infrastructure
2,3,nvidia corporation,$1.186 t,nvda,united states,technology,semiconductors
3,4,broadcom inc.,$495.95 b,avgo,united states,technology,semiconductors
4,5,taiwan semiconductor manufacturing company lim...,$487.64 b,2330,taiwan,technology,semiconductors

In [ ]:
# Remove caracteres especiais de colunas com Strings
companies_df[string_columns] = companies_df[string_columns].apply(lambda x: x.str.replace(r'[^a-z0-9\s]', '', regex=True))

In [ ]:
companies_df.head()

,ranking,company,marketcap,stock,country,sector,industry
0,1,apple inc,2866 t,aapl,united states,technology,consumer electronics
1,2,microsoft corporation,2755 t,msft,united states,technology,softwareinfrastructure
2,3,nvidia corporation,1186 t,nvda,united states,technology,semiconductors
3,4,broadcom inc,49595 b,avgo,united states,technology,semiconductors
4,5,taiwan semiconductor manufacturing company lim...,48764 b,2330,taiwan,technology,semiconductors

In [ ]:
companies_df.tail()

,ranking,company,marketcap,stock,country,sector,industry
995,996henan thinker automatic equipment coltd8254...,NaN,NaN,NaN,NaN,NaN,NaN
996,997transcosmos inc8195 m9715japantechnologyinf...,NaN,NaN,NaN,NaN,NaN,NaN
997,998,yeahka ltd,8193 m,9923,china,technology,softwareinfrastructure
998,999,beijing wanji technology co ltd,8161 m,300552,china,technology,scientific technical instruments
999,1000fujian foxit software development joint st...,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
companies_df['marketcap']

0       2866 t
1       2755 t
2       1186 t
3      49595 b
4      48764 b
        ...
995        NaN
996        NaN
997     8193 m
998     8161 m
999        NaN
Name: marketcap, Length: 1000, dtype: object

In [ ]:
def parse_marketcap(marketcap_str):
    if pd.isna(marketcap_str) or not isinstance(marketcap_str, str):
        return np.nan
    marketcap_str = marketcap_str.replace('$', '').strip().lower()
    # cuida de casos em que a unidade está grudada com o número
    try:
        value = float(marketcap_str[:-1])
        unit = marketcap_str[-1]
    except ValueError:
        return np.nan # se falhar, retorna NaN

    if unit == 't':
        return value * 1000 # converte trilhões para bilhões
    elif unit == 'b':
        return value # valor já é em bilhões
    elif unit == 'm':
        return value / 1000 # Converte milhões para bilhões
    else:
        return np.nan # cuida de casos em que a unidade não é t, b ou m

In [ ]:
companies_df['marketcap_billion'] = companies_df['marketcap'].apply(parse_marketcap)

In [ ]:
# calcular o marketcap total e imprimir
total_marketcap_billion = companies_df['marketcap_billion'].sum()

In [ ]:
print(f"Valor total estimado das companhias: {total_marketcap_billion:,.2f} Bilhões de dólares")

Valor total estimado das companhias: 7,556,591.11 Bilhões de dólares

In [ ]:
companies_df[['company', 'marketcap', 'marketcap_billion']].head()

,company,marketcap,marketcap_billion
0,apple inc,2866 t,2866000.0
1,microsoft corporation,2755 t,2755000.0
2,nvidia corporation,1186 t,1186000.0
3,broadcom inc,49595 b,49595.0
4,taiwan semiconductor manufacturing company lim...,48764 b,48764.0

In [ ]:
import random # importa o random para a funcao sample

random.sample(range(1, 40), 5) # Chama a sample

[38, 13, 8, 4, 7]

In [ ]:
import random

random.choices(["H", "T"], k=10) # Samples from a list of strings "H" and "T" 10 times with replacement.

['T', 'T', 'T', 'T', 'T', 'H', 'T', 'T', 'H', 'H']

In [ ]:
import random
random.choices(range(1, 7), k=10)

[4, 3, 6, 2, 6, 2, 6, 2, 2, 6]

In [ ]:
import numpy as np
import matplotlib.pyplot as plt

# função para simular lançamentos de moeda
def simular_lancamentos(n):
    # Simular n lançamentos de moeda (0 para "cara", 1 para "coroa")
    resultados = np.random.randint(0, 2, size=n)

    # Calcular a frequência relativa
    frequencia_cara = np.sum(resultados == 0) / n
    frequencia_coroa = np.sum(resultados == 1) / n