Atividade 2:

Baixe o dataset Titanic da base de dados Kaggle (https://www.kaggle.com/datasets/brendan45774/test-file)


# Passo 1: Carregar o dataset


# Passo 2: Explorar o dataset

# Passo 3: Identificar e remover duplicatas

# Verificar se há duplicatas

# Passo 4: Preencher valores ausentes

# Verificar valores ausentes por coluna


# Verificar se ainda há valores ausentes

# Exibir as primeiras linhas do DataFrame limpo

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
titanic_df = pd.read_csv('/content/drive/MyDrive/ColabNotebooks/Mackenzie/4Semestre/AnaliseDeDados/Aula3/Titanic.csv')

In [ ]:
titanic_df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,0,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,893,1,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,894,0,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
3,895,0,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
4,896,1,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S

In [ ]:
titanic_df.shape

(418, 12)

In [ ]:
titanic_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 418 entries, 0 to 417
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  418 non-null    int64
 1   Survived     418 non-null    int64
 2   Pclass       418 non-null    int64
 3   Name         418 non-null    object
 4   Sex          418 non-null    object
 5   Age          332 non-null    float64
 6   SibSp        418 non-null    int64
 7   Parch        418 non-null    int64
 8   Ticket       418 non-null    object
 9   Fare         417 non-null    float64
 10  Cabin        91 non-null     object
 11  Embarked     418 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 39.3+ KB

In [ ]:
titanic_df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age             86
SibSp            0
Parch            0
Ticket           0
Fare             1
Cabin          327
Embarked         0
dtype: int64

In [ ]:
titanic_df.dtypes

PassengerId      int64
Survived         int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Cabin           object
Embarked        object
dtype: object

In [ ]:
titanic_df['Embarked'].value_counts()
# esses valores são os pontos de embarque dos passageiros!

# S: Southampton
# C: Cherbourg
# Q: Queenstown

Embarked
S    270
C    102
Q     46
Name: count, dtype: int64

In [ ]:
titanic_df.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,418.000000,418.000000,418.000000,332.000000,418.000000,418.000000,417.000000
mean,1100.500000,0.363636,2.265550,30.272590,0.447368,0.392344,35.627188
std,120.810458,0.481622,0.841838,14.181209,0.896760,0.981429,55.907576
min,892.000000,0.000000,1.000000,0.170000,0.000000,0.000000,0.000000
25%,996.250000,0.000000,1.000000,21.000000,0.000000,0.000000,7.895800
50%,1100.500000,0.000000,3.000000,27.000000,0.000000,0.000000,14.454200
75%,1204.750000,1.000000,3.000000,39.000000,1.000000,0.000000,31.500000
max,1309.000000,1.000000,3.000000,76.000000,8.000000,9.000000,512.329200

In [ ]:
titanic_df[titanic_df['Fare'].isnull()]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
152,1044,0,3,"Storey, Mr. Thomas",male,60.5,0,0,3701,NaN,NaN,S



---

Identificando e Removendo duplicatas

In [ ]:
titanic_df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,0,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,893,1,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,894,0,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
3,895,0,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
4,896,1,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S

In [ ]:
titanic_df.duplicated().sum()
# não há nenhuma linha igual à outra (duplicatas)!

np.int64(0)

In [ ]:
titanic_df['PassengerId'].duplicated().sum()

np.int64(0)

In [ ]:
titanic_df['Name'].duplicated().sum()

np.int64(0)

In [ ]:
titanic_df['Age'].duplicated().sum()
# pessoas diferentes podem ter a mesma idade!

np.int64(338)

In [ ]:
titanic_df['Ticket'].duplicated().sum()
# a coluna 'Ticket' tem 55 valores duplicados!
# Familias ou casais podem compartilhar do mesmo ticket, então vou manter as duplicatas

np.int64(55)

In [ ]:
titanic_df['Fare'].duplicated().sum()
# pessoas diferentes podem pagar o mesmo valor!

np.int64(248)

In [ ]:
titanic_df[['Fare']].value_counts()
# criando um filtro para os valores de 'Fare' duplicados

Fare
7.7500      21
26.0000     19
8.0500      17
13.0000     17
7.8958      11
            ..
135.6333     1
227.5250     1
211.3375     1
247.5208     1
512.3292     1
Name: count, Length: 169, dtype: int64

In [ ]:
titanic_df.loc[titanic_df['Fare'] == 7.8958]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
10,902,0,3,"Ilieff, Mr. Ylio",male,NaN,0,0,349220,7.8958,NaN,S
56,948,0,3,"Cor, Mr. Bartol",male,35.0,0,0,349230,7.8958,NaN,S
60,952,0,3,"Dika, Mr. Mirko",male,17.0,0,0,349232,7.8958,NaN,S
71,963,0,3,"Minkoff, Mr. Lazar",male,21.0,0,0,349211,7.8958,NaN,S
83,975,0,3,"Demetri, Mr. Marinko",male,NaN,0,0,349238,7.8958,NaN,S
134,1026,0,3,"Dintcheff, Mr. Valtcho",male,43.0,0,0,349226,7.8958,NaN,S
151,1043,0,3,"Matinoff, Mr. Nicola",male,NaN,0,0,349255,7.8958,NaN,C
209,1101,0,3,"Delalic, Mr. Redjo",male,25.0,0,0,349250,7.8958,NaN,S
265,1157,0,3,"Lyntakoff, Mr. Stanko",male,NaN,0,0,349235,7.8958,NaN,S
295,1187,0,3,"Angheloff, Mr. Minko",male,26.0,0,0,349202,7.8958,NaN,S
334,1226,0,3,"Cor, Mr. Ivan",male,27.0,0,0,349229,7.8958,NaN,S



---

- Limpeza de Dados: Verificação de duplicatas

Antes de verificar e preencher os valores ausentes, eu chequei o dataset por valores duplicados. Enquanto algumas colunas como 'Ticket' possuem duplicatas (o que é esperado porque famílias viajaram juntas e compartilharam tickets), a verificação em todas as colunas e a chave primária PassengerID me revelou 0 linhas duplicadas. Portanto, nenhuma linha deve ser removida para preservar a integridade do dataset.

In [ ]:
# Vertificar linhas inteiras duplicadas
full_duplicates = titanic_df.duplicated().sum()

# Checar PassengerIDs duplicados (chave primária)
id_duplicates = titanic_df['PassengerId'].duplicated().sum()

print(f"Total de linhas duplicadas: {full_duplicates}")
print(f"Total de PassengerIDs duplicados: {id_duplicates}")

Total de linhas duplicadas: 0
Total de PassengerIDs duplicados: 0



---

- Cuidando dos valores ausentes

In [ ]:
titanic_df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age             86
SibSp            0
Parch            0
Ticket           0
Fare             1
Cabin          327
Embarked         0
dtype: int64

In [ ]:
titanic_df['Age'].isna()

0      False
1      False
2      False
3      False
4      False
       ...
413     True
414    False
415    False
416     True
417     True
Name: Age, Length: 418, dtype: bool

In [ ]:
titanic_df['Age'].loc[titanic_df['Age'].isna()]

10    NaN
22    NaN
29    NaN
33    NaN
36    NaN
       ..
408   NaN
410   NaN
413   NaN
416   NaN
417   NaN
Name: Age, Length: 86, dtype: float64

**Preencher valores ausentes de idade com a mediana da coluna é uma boa alternativa.**

Porque a mediana? Porque a mediana é robusta contra outliers, diferente da média, que pode ser facilmente enviesada por causa de outliers (pessoas muito novas ou pessoas muito velhas).

In [ ]:
titanic_df['Age'].describe()

count    332.000000
mean      30.272590
std       14.181209
min        0.170000
25%       21.000000
50%       27.000000
75%       39.000000
max       76.000000
Name: Age, dtype: float64

In [ ]:
age_mean = titanic_df['Age'].mean()
age_median = titanic_df['Age'].median()

print('A média das idades é igual a: ', age_mean)
print('A mediana das idades é igual a: ', age_median)

A média das idades é igual a:  30.272590361445783
A mediana das idades é igual a:  27.0

In [ ]:
titanic_df['Age'] = titanic_df['Age'].fillna(value=age_median)

# preenchendo as idades vazias com a mediana

In [ ]:
titanic_df['Age'].isnull().sum()
# agora temos 0 valores ausentes para as idades!

np.int64(0)

In [ ]:
titanic_df.loc[titanic_df['Fare'].isna()]

# esse é o único valor ausente da coluna!

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
152,1044,0,3,"Storey, Mr. Thomas",male,60.5,0,0,3701,NaN,NaN,S

In [ ]:
pclass_grp = titanic_df.groupby('Pclass')

In [ ]:
pclass_grp.get_group(3).describe()

# Como a 'Fare' ausente é de um passageiro de terceira classe,
# agrupei as classes para calcular a mediana das 'Fares' dessa classe

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,218.000000,218.000000,218.0,218.000000,218.000000,218.000000,217.000000
mean,1094.178899,0.330275,3.0,25.009541,0.463303,0.417431,12.459678
std,120.188830,0.471395,0.0,8.726613,1.107591,1.165980,10.803698
min,892.000000,0.000000,3.0,0.170000,0.000000,0.000000,3.170800
25%,994.250000,0.000000,3.0,21.250000,0.000000,0.000000,7.750000
50%,1091.500000,0.000000,3.0,27.000000,0.000000,0.000000,7.895800
75%,1191.750000,1.000000,3.0,27.000000,1.000000,0.000000,14.400000
max,1309.000000,1.000000,3.0,60.500000,8.000000,9.000000,69.550000

In [ ]:
third_class_mean = pclass_grp['Fare'].get_group(3).mean()
third_class_median = pclass_grp['Fare'].get_group(3).median()

print('A média das Fares da terceira classe é: ', third_class_mean)
print('A mediana das Fares da terceira classe é: ', third_class_median)
# aqui podemos ver como os outliers afetam de forma significativa a média!

A média das Fares da terceira classe é:  12.459677880184334
A mediana das Fares da terceira classe é:  7.8958

In [ ]:
titanic_df['Fare'] = titanic_df['Fare'].fillna(value=third_class_median)
# agora estou preenchendo o valor ausente da coluna 'Fare' com a mediana da terceira classe

In [ ]:
titanic_df.loc[152]
# agora a 'Fare' está preenchida!

PassengerId                  1044
Survived                        0
Pclass                          3
Name           Storey, Mr. Thomas
Sex                          male
Age                          60.5
SibSp                           0
Parch                           0
Ticket                       3701
Fare                       7.8958
Cabin                         NaN
Embarked                        S
Name: 152, dtype: object

In [ ]:
titanic_df.loc[titanic_df['Cabin'].isna()]
# praticamente 80% dos valores para a cabine estão vazios!

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,0,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,893,1,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,894,0,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
3,895,0,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
4,896,1,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
412,1304,1,3,"Henriksson, Miss. Jenny Lovisa",female,28.0,0,0,347086,7.7750,NaN,S
413,1305,0,3,"Spector, Mr. Woolf",male,27.0,0,0,A.5. 3236,8.0500,NaN,S
415,1307,0,3,"Saether, Mr. Simon Sivertsen",male,38.5,0,0,SOTON/O.Q. 3101262,7.2500,NaN,S
416,1308,0,3,"Ware, Mr. Frederick",male,27.0,0,0,359309,8.0500,NaN,S
417,1309,0,3,"Peter, Master. Michael J",male,27.0,1,1,2668,22.3583,NaN,C

In [ ]:
# acredito que devo remover a coluna 'Cabin', pois preenchê-la não nos daria informação confiável.
# Portanto, vou optar por remover do DataFrame.

titanic_df = titanic_df.drop(columns=['Cabin'])

In [ ]:
titanic_df.isnull().sum()
# agora não temos mais nenhum valor ausente!

PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Embarked       0
dtype: int64

In [ ]:
titanic_df.shape
# mesmo número de linhas, uma coluna a menos. Tudo certo!

(418, 11)

---

- Passando todos os textos para minúsculo

In [ ]:
titanic_df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked
0,892,0,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,Q
1,893,1,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,S
2,894,0,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,Q
3,895,0,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,S
4,896,1,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,S

In [ ]:
titanic_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 418 entries, 0 to 417
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  418 non-null    int64
 1   Survived     418 non-null    int64
 2   Pclass       418 non-null    int64
 3   Name         418 non-null    object
 4   Sex          418 non-null    object
 5   Age          418 non-null    float64
 6   SibSp        418 non-null    int64
 7   Parch        418 non-null    int64
 8   Ticket       418 non-null    object
 9   Fare         418 non-null    float64
 10  Embarked     418 non-null    object
dtypes: float64(2), int64(5), object(4)
memory usage: 36.1+ KB

In [ ]:
titanic_df['Sex'].value_counts()

Sex
male      266
female    152
Name: count, dtype: int64

In [ ]:
titanic_df['Name'] = titanic_df['Name'].str.lower()
titanic_df['Ticket'] = titanic_df['Ticket'].str.lower()
titanic_df['Embarked'] = titanic_df['Embarked'].str.lower()

In [ ]:
titanic_df.head(10)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked
0,892,0,3,"kelly, mr. james",male,34.5,0,0,330911,7.8292,q
1,893,1,3,"wilkes, mrs. james (ellen needs)",female,47.0,1,0,363272,7.0000,s
2,894,0,2,"myles, mr. thomas francis",male,62.0,0,0,240276,9.6875,q
3,895,0,3,"wirz, mr. albert",male,27.0,0,0,315154,8.6625,s
4,896,1,3,"hirvonen, mrs. alexander (helga e lindqvist)",female,22.0,1,1,3101298,12.2875,s
5,897,0,3,"svensson, mr. johan cervin",male,14.0,0,0,7538,9.2250,s
6,898,1,3,"connolly, miss. kate",female,30.0,0,0,330972,7.6292,q
7,899,0,2,"caldwell, mr. albert francis",male,26.0,1,1,248738,29.0000,s
8,900,1,3,"abrahim, mrs. joseph (sophie halaut easu)",female,18.0,0,0,2657,7.2292,c
9,901,0,3,"davies, mr. john samuel",male,21.0,2,0,a/4 48871,24.1500,s

In [ ]:
titanic_df.tail()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked
413,1305,0,3,"spector, mr. woolf",male,27.0,0,0,a.5. 3236,8.0500,s
414,1306,1,1,"oliva y ocana, dona. fermina",female,39.0,0,0,pc 17758,108.9000,c
415,1307,0,3,"saether, mr. simon sivertsen",male,38.5,0,0,soton/o.q. 3101262,7.2500,s
416,1308,0,3,"ware, mr. frederick",male,27.0,0,0,359309,8.0500,s
417,1309,0,3,"peter, master. michael j",male,27.0,1,1,2668,22.3583,c



---


- Classificação das variáveis do dataset Titanic

Categórica/Qualitativa Nominal: PassengerID, Survived, Name, Sex, Ticket, Embarked

Categórica/Qualitativa Ordinal: Pclass

Numérica/Quantitativa Discreta: SibSp, Parch

Numérica/Quantitativa Contínua: Age, Fare

---

- O DataFrame foi limpo com sucesso!