Atividade 1:

Dados fictícios de uma empresa e de um hotel:

- Abra o arquivo csv em seu google colab
- Confira a estrutura dos dados utilizando as funções str(empresa), head(empresa), tail(empresa). Avalie se o conjunto de dados se encontra dentro dos padrões esperados para análise.
- Classifique  cada uma das variáveis.
- Qual a classificação da variável Inst? Modifique para ordem.
-Crie uma nova variável denominada Idade a partir de Anos e Meses.

Faça isso para cada um dos datasets.

In [1]:
import pandas as pd
import numpy as np

In [2]:
empresa_df = pd.read_csv('/content/drive/MyDrive/ColabNotebooks/Mackenzie/4Semestre/AnaliseDeDados/Aula3/empresadataset.csv')
hotel_df = pd.read_excel('/content/drive/MyDrive/ColabNotebooks/Mackenzie/4Semestre/AnaliseDeDados/Aula3/hoteldatasetExcel.xlsx')

In [3]:
empresa_df.shape

(36, 8)

In [4]:
hotel_df.shape

(525, 9)

In [5]:
empresa_df.head()

   Funcionario Est.civil     Inst  Filhos  Salario  Anos  Meses    Regiao
0            1  solteiro  1o Grau     NaN     4.00    26      3  interior
1            2    casado  1o Grau     1.0     4.56    32     10   capital
2            3    casado  1o Grau     2.0     5.25    36      5   capital
3            4  solteiro  2o Grau     NaN     5.73    20     10     outro
4            5  solteiro  1o Grau     NaN     6.26    40      7     outro

In [6]:
empresa_df.tail()

    Funcionario Est.civil      Inst  Filhos  Salario  Anos  Meses    Regiao
31           32    casado   2o Grau     1.0    16.61    36      4  interior
32           33    casado  Superior     3.0    17.26    43      7   capital
33           34  solteiro  Superior     NaN    18.75    33      7   capital
34           35    casado   2o Grau     2.0    19.40    48     11   capital
35           36    casado  Superior     3.0    23.30    42      2  interior

In [7]:
hotel_df.head()

,Unnamed: 0,Name,Place,Type,Price,ReviewsCount,Rating,City,State
0,0,BUNK Hotel Amsterdam,"Amsterdam Noord, Amsterdam",Bunk Pod for 2,"? 7,887",778.0,8.4,Amsterdam Noord,Amsterdam
1,1,YOTEL Amsterdam,"Amsterdam Noord, Amsterdam",Premium Double Room,"? 15,267",500.0,8.1,Amsterdam Noord,Amsterdam
2,2,Multatuli Hotel,"Amsterdam City Center, Amsterdam",Double Room,"? 13,063",1605.0,7.4,Amsterdam City Center,Amsterdam
3,3,nhow Amsterdam Rai,"Zuideramstel, Amsterdam",nhow Double or Twin Room with View,"? 12,854",500.0,9.0,Zuideramstel,Amsterdam
4,4,Motel One Amsterdam,"Zuideramstel, Amsterdam",Double Room,"? 9,471",500.0,8.8,Zuideramstel,Amsterdam

In [8]:
str(empresa_df.dtypes)
# aparentemente terei que converter o tipo de dado da coluna 'Filhos' para int64, porque não se tem "meio" filho.
# acho que os tipos de dados das outras colunas estão adequados.

'Funcionario      int64\nEst.civil       object\nInst            object\nFilhos         float64\nSalario        float64\nAnos             int64\nMeses            int64\nRegiao          object\ndtype: object'

In [9]:
# Verificar valores ausentes
filt_filhos_null = empresa_df['Filhos'].isnull()
print("\nImprimindo a coluna 'Filhos' com valores booleanos indicando NaNs:")
print(filt_filhos_null)

Imprimindo a coluna 'Filhos' com valores booleanos indicando NaNs:
0      True
1     False
2     False
3      True
4      True
5     False
6      True
7      True
8     False
9      True
10    False
11     True
12     True
13    False
14    False
15     True
16    False
17    False
18     True
19     True
20    False
21     True
22     True
23    False
24    False
25    False
26     True
27    False
28    False
29    False
30     True
31    False
32    False
33     True
34    False
35    False
Name: Filhos, dtype: bool

In [10]:
empresa_df.loc[filt_filhos_null, 'Filhos']
# imprimindo todas as linhas em que o numero de filhos não foi informado.
# como em todos esses casos as pessoas são solteiras, acredito que podemos afirmar que eles têm 0 filhos.

0    NaN
3    NaN
4    NaN
6    NaN
7    NaN
9    NaN
11   NaN
12   NaN
15   NaN
18   NaN
19   NaN
21   NaN
22   NaN
26   NaN
30   NaN
33   NaN
Name: Filhos, dtype: float64

In [11]:
empresa_df.loc[filt_filhos_null, 'Filhos'] = 0
# atualizando o dado da coluna 'filhos' onde o valor é NaN

In [12]:
empresa_df.loc[filt_filhos_null, 'Filhos']
# mostrando as linhas atualizadas

0     0.0
3     0.0
4     0.0
6     0.0
7     0.0
9     0.0
11    0.0
12    0.0
15    0.0
18    0.0
19    0.0
21    0.0
22    0.0
26    0.0
30    0.0
33    0.0
Name: Filhos, dtype: float64

In [13]:
empresa_df.head()

   Funcionario Est.civil     Inst  Filhos  Salario  Anos  Meses    Regiao
0            1  solteiro  1o Grau     0.0     4.00    26      3  interior
1            2    casado  1o Grau     1.0     4.56    32     10   capital
2            3    casado  1o Grau     2.0     5.25    36      5   capital
3            4  solteiro  2o Grau     0.0     5.73    20     10     outro
4            5  solteiro  1o Grau     0.0     6.26    40      7     outro

In [14]:
empresa_df['Filhos'] = empresa_df['Filhos'].astype(int)
# convertendo todos os valores na coluna 'Filhos' para int
empresa_df.head()

   Funcionario Est.civil     Inst  Filhos  Salario  Anos  Meses    Regiao
0            1  solteiro  1o Grau       0     4.00    26      3  interior
1            2    casado  1o Grau       1     4.56    32     10   capital
2            3    casado  1o Grau       2     5.25    36      5   capital
3            4  solteiro  2o Grau       0     5.73    20     10     outro
4            5  solteiro  1o Grau       0     6.26    40      7     outro

In [15]:
empresa_df.dtypes

Funcionario      int64
Est.civil       object
Inst            object
Filhos           int64
Salario        float64
Anos             int64
Meses            int64
Regiao          object
dtype: object

In [16]:
empresa_df

    Funcionario Est.civil      Inst  Filhos  Salario  Anos  Meses    Regiao
0             1  solteiro   1o Grau       0     4.00    26      3  interior
1             2    casado   1o Grau       1     4.56    32     10   capital
2             3    casado   1o Grau       2     5.25    36      5   capital
3             4  solteiro   2o Grau       0     5.73    20     10     outro
4             5  solteiro   1o Grau       0     6.26    40      7     outro
5             6    casado   1o Grau       0     6.66    28      0  interior
6             7  solteiro   1o Grau       0     6.86    41      0  interior
7             8  solteiro   1o Grau       0     7.39    43      4   capital
8             9    casado   2o Grau       1     7.59    34     10   capital
9            10  solteiro   2o Grau       0     7.44    23      6     outro
10           11    casado   2o Grau       2     8.12    33      6  interior
11           12  solteiro   1o Grau       0     8.46    27     11   capital
12           13  solteiro   2o Grau       0     8.74    37      5     outro
13           14    casado   1o Grau       3     8.95    44      2     outro
14           15    casado   2o Grau       0     9.13    30      5  interior
15           16  solteiro   2o Grau       0     9.35    38      8     outro
16           17    casado   2o Grau       1     9.77    31      7   capital
17           18    casado   1o Grau       2     9.80    39      7     outro
18           19  solteiro  Superior       0    10.53    25      8  interior
19           20  solteiro   2o Grau       0    10.76    37      4  interior
20           21    casado   2o Grau       1    11.06    30      9     outro
21           22  solteiro   2o Grau       0    11.59    34      2   capital
22           23  solteiro   1o Grau       0    12.00    41      0     outro
23           24    casado  Superior       0    12.79    26      1     outro
24           25    casado   2o Grau       2    13.23    32      5  interior
25           26    casado   2o Grau       2    13.60    35      0     outro
26           27  solteiro   1o Grau       0    13.85    46      7     outro
27           28    casado   2o Grau       0    14.69    29      8  interior
28           29    casado   2o Grau       5    14.71    40      6  interior
29           30    casado   2o Grau       2    15.99    35     10   capital
30           31  solteiro  Superior       0    16.22    31      5     outro
31           32    casado   2o Grau       1    16.61    36      4  interior
32           33    casado  Superior       3    17.26    43      7   capital
33           34  solteiro  Superior       0    18.75    33      7   capital
34           35    casado   2o Grau       2    19.40    48     11   capital
35           36    casado  Superior       3    23.30    42      2  interior

- Transformando a coluna 'Funcionario' nos índices do dataset

In [17]:
empresa_df.set_index('Funcionario', inplace=True)
empresa_df.head()
# agora 'Funcionario' é o índice!

            Est.civil     Inst  Filhos  Salario  Anos  Meses    Regiao
Funcionario
1            solteiro  1o Grau       0     4.00    26      3  interior
2              casado  1o Grau       1     4.56    32     10   capital
3              casado  1o Grau       2     5.25    36      5   capital
4            solteiro  2o Grau       0     5.73    20     10     outro
5            solteiro  1o Grau       0     6.26    40      7     outro

- Limpando o dataset hotel

In [18]:
hotel_df.head()

,Unnamed: 0,Name,Place,Type,Price,ReviewsCount,Rating,City,State
0,0,BUNK Hotel Amsterdam,"Amsterdam Noord, Amsterdam",Bunk Pod for 2,"? 7,887",778.0,8.4,Amsterdam Noord,Amsterdam
1,1,YOTEL Amsterdam,"Amsterdam Noord, Amsterdam",Premium Double Room,"? 15,267",500.0,8.1,Amsterdam Noord,Amsterdam
2,2,Multatuli Hotel,"Amsterdam City Center, Amsterdam",Double Room,"? 13,063",1605.0,7.4,Amsterdam City Center,Amsterdam
3,3,nhow Amsterdam Rai,"Zuideramstel, Amsterdam",nhow Double or Twin Room with View,"? 12,854",500.0,9.0,Zuideramstel,Amsterdam
4,4,Motel One Amsterdam,"Zuideramstel, Amsterdam",Double Room,"? 9,471",500.0,8.8,Zuideramstel,Amsterdam

In [19]:
hotel_df.rename(columns={'Unnamed: 0': 'Hotel_ID'}, inplace=True)
# renomeando a coluna 'Unnamed: 0' para 'Hotel_ID'
hotel_df.set_index('Hotel_ID', inplace=True)

# renomeando a coluna 'Unnamed: 0' para 'Hotel_ID' e transformando no ID do dataset

In [20]:
hotel_df.head()

,Name,Place,Type,Price,ReviewsCount,Rating,City,State
Hotel_ID,,,,,,,,
0,BUNK Hotel Amsterdam,"Amsterdam Noord, Amsterdam",Bunk Pod for 2,"? 7,887",778.0,8.4,Amsterdam Noord,Amsterdam
1,YOTEL Amsterdam,"Amsterdam Noord, Amsterdam",Premium Double Room,"? 15,267",500.0,8.1,Amsterdam Noord,Amsterdam
2,Multatuli Hotel,"Amsterdam City Center, Amsterdam",Double Room,"? 13,063",1605.0,7.4,Amsterdam City Center,Amsterdam
3,nhow Amsterdam Rai,"Zuideramstel, Amsterdam",nhow Double or Twin Room with View,"? 12,854",500.0,9.0,Zuideramstel,Amsterdam
4,Motel One Amsterdam,"Zuideramstel, Amsterdam",Double Room,"? 9,471",500.0,8.8,Zuideramstel,Amsterdam

In [21]:
hotel_df.dtypes

# vendo os tipos de dados, pude notar que a coluna 'Price' deve ser convertida para float64
# a coluna 'ReviewsCount' deve ser convertida para int64

Name             object
Place            object
Type             object
Price            object
ReviewsCount    float64
Rating          float64
City             object
State            object
dtype: object

In [22]:
hotel_df['Price']

Hotel_ID
0       ? 7,887
1      ? 15,267
2      ? 13,063
3      ? 12,854
4       ? 9,471
         ...
520     ? 8,899
521    ? 10,205
522     ? 6,123
523     ? 7,789
524     ? 6,870
Name: Price, Length: 525, dtype: object

In [23]:
# vou renomear a coluna 'Price' para 'Price_EUR', pois todos os hotéis ficam na europa
hotel_df.rename(columns={'Price': 'Price_EUR'}, inplace=True)

In [24]:
# Contagem de valores ausentes na coluna 'Price_EUR'
hotel_df['Price_EUR'].isnull().sum()

# temos 0 linhas com valores nulos!

np.int64(0)

In [25]:
hotel_df.head()

,Name,Place,Type,Price_EUR,ReviewsCount,Rating,City,State
Hotel_ID,,,,,,,,
0,BUNK Hotel Amsterdam,"Amsterdam Noord, Amsterdam",Bunk Pod for 2,"? 7,887",778.0,8.4,Amsterdam Noord,Amsterdam
1,YOTEL Amsterdam,"Amsterdam Noord, Amsterdam",Premium Double Room,"? 15,267",500.0,8.1,Amsterdam Noord,Amsterdam
2,Multatuli Hotel,"Amsterdam City Center, Amsterdam",Double Room,"? 13,063",1605.0,7.4,Amsterdam City Center,Amsterdam
3,nhow Amsterdam Rai,"Zuideramstel, Amsterdam",nhow Double or Twin Room with View,"? 12,854",500.0,9.0,Zuideramstel,Amsterdam
4,Motel One Amsterdam,"Zuideramstel, Amsterdam",Double Room,"? 9,471",500.0,8.8,Zuideramstel,Amsterdam

In [26]:
# tirando o símbolo '?' da coluna 'Price'

hotel_df['Price_EUR'] = hotel_df['Price_EUR'].str.replace('?', '')

In [27]:
hotel_df['Price_EUR']

Hotel_ID
0        7,887
1       15,267
2       13,063
3       12,854
4        9,471
        ...
520      8,899
521     10,205
522      6,123
523      7,789
524      6,870
Name: Price_EUR, Length: 525, dtype: object

In [28]:
hotel_df['Price_EUR'] = hotel_df['Price_EUR'].str.replace(',', '').astype(float)

# convertendo os valores na coluna 'Price_EUR' para float

In [29]:
# Contagem de valores ausentes na coluna 'ReviewsCount'

print("\nNúmero de linhas com valores ausentes na coluna 'ReviewsCount':")
print(hotel_df['ReviewsCount'].isnull().sum())

hotel_df['ReviewsCount'].isnull().sum()

# temos 13 linhas com valores nulos!

Número de linhas com valores ausentes na coluna 'ReviewsCount':
13

np.int64(13)

In [30]:
# visualizando as linhas com valores ausentes na coluna 'ReviewsCount'

filt_reviews_null = (hotel_df['ReviewsCount'].isnull() == True)
print("\nImprimindo a coluna 'ReviewsCount' com valores booleanos indicando NaNs:")
hotel_df.loc[filt_reviews_null, 'ReviewsCount']

Imprimindo a coluna 'ReviewsCount' com valores booleanos indicando NaNs:

Hotel_ID
9     NaN
251   NaN
439   NaN
445   NaN
474   NaN
475   NaN
476   NaN
477   NaN
478   NaN
479   NaN
480   NaN
481   NaN
482   NaN
Name: ReviewsCount, dtype: float64

In [31]:
# substituindo NaN com 0 e convertendo a coluna para int
hotel_df['ReviewsCount'] = hotel_df['ReviewsCount'].fillna(0).astype(int)

In [32]:
hotel_df.loc[filt_reviews_null, 'ReviewsCount']
# agora os valores que eram NaN se tornaram zero!

Hotel_ID
9      0
251    0
439    0
445    0
474    0
475    0
476    0
477    0
478    0
479    0
480    0
481    0
482    0
Name: ReviewsCount, dtype: int64

In [33]:
hotel_df.dtypes
# agora a coluna 'ReviewsCount' é do tipo int!

Name             object
Place            object
Type             object
Price_EUR       float64
ReviewsCount      int64
Rating          float64
City             object
State            object
dtype: object

In [34]:
hotel_df['Type']

Hotel_ID
0                          Bunk Pod for 2
1                     Premium Double Room
2                             Double Room
3      nhow Double or Twin Room with View
4                             Double Room
                      ...
520                    Superior Apartment
521                  Standard Double Room
522     Double Room with Private Bathroom
523                    Standard Twin Room
524                           Double Room
Name: Type, Length: 525, dtype: object

In [35]:
hotel_df.head()

,Name,Place,Type,Price_EUR,ReviewsCount,Rating,City,State
Hotel_ID,,,,,,,,
0,BUNK Hotel Amsterdam,"Amsterdam Noord, Amsterdam",Bunk Pod for 2,7887.0,778,8.4,Amsterdam Noord,Amsterdam
1,YOTEL Amsterdam,"Amsterdam Noord, Amsterdam",Premium Double Room,15267.0,500,8.1,Amsterdam Noord,Amsterdam
2,Multatuli Hotel,"Amsterdam City Center, Amsterdam",Double Room,13063.0,1605,7.4,Amsterdam City Center,Amsterdam
3,nhow Amsterdam Rai,"Zuideramstel, Amsterdam",nhow Double or Twin Room with View,12854.0,500,9.0,Zuideramstel,Amsterdam
4,Motel One Amsterdam,"Zuideramstel, Amsterdam",Double Room,9471.0,500,8.8,Zuideramstel,Amsterdam



---


- Classificação das variáveis do dataset empresa

Categórica/Qualitativa Nominal: Funcionario (ID), Est.civil, Regiao

Categórica/Qualitativa Ordinal: Inst

Numérica/Quantitativa Discreta: Filhos, Anos, Meses

Numérica/Quantitativa Contínua: Salario

- Classificação das variáveis do dataset hotel

Categórica/Qualitativa Nominal: Hotel_ID, Name, Place, Type, City, State

Categórica/Qualitativa Ordinal:

Numérica/Quantitativa Discreta: ReviewsCount

Numérica/Quantitativa Contínua: Price_EUR, Rating



---

- Modificando a variável Inst para ordem

In [36]:
empresa_df.tail(10)

            Est.civil      Inst  Filhos  Salario  Anos  Meses    Regiao
Funcionario
27           solteiro   1o Grau       0    13.85    46      7     outro
28             casado   2o Grau       0    14.69    29      8  interior
29             casado   2o Grau       5    14.71    40      6  interior
30             casado   2o Grau       2    15.99    35     10   capital
31           solteiro  Superior       0    16.22    31      5     outro
32             casado   2o Grau       1    16.61    36      4  interior
33             casado  Superior       3    17.26    43      7   capital
34           solteiro  Superior       0    18.75    33      7   capital
35             casado   2o Grau       2    19.40    48     11   capital
36             casado  Superior       3    23.30    42      2  interior

In [37]:
# 1. Definir a ordem lógica correta das categorias
ordem_educacao = ['1o Grau', '2o Grau', 'Superior']

# 2. Converter a coluna para categorias ordenadas
empresa_df['Inst'] = pd.Categorical(empresa_df['Inst'], categories=ordem_educacao, ordered=True)

In [38]:
empresa_df.dtypes
# agora a coluna 'Inst' é do tipo category!

Est.civil      object
Inst         category
Filhos          int64
Salario       float64
Anos            int64
Meses           int64
Regiao         object
dtype: object

In [39]:
empresa_df.sort_values('Inst')
# agora podemos ordenar pela categoria 'Inst'!

            Est.civil      Inst  Filhos  Salario  Anos  Meses    Regiao
Funcionario
1            solteiro   1o Grau       0     4.00    26      3  interior
27           solteiro   1o Grau       0    13.85    46      7     outro
23           solteiro   1o Grau       0    12.00    41      0     outro
14             casado   1o Grau       3     8.95    44      2     outro
12           solteiro   1o Grau       0     8.46    27     11   capital
8            solteiro   1o Grau       0     7.39    43      4   capital
18             casado   1o Grau       2     9.80    39      7     outro
6              casado   1o Grau       0     6.66    28      0  interior
5            solteiro   1o Grau       0     6.26    40      7     outro
2              casado   1o Grau       1     4.56    32     10   capital
3              casado   1o Grau       2     5.25    36      5   capital
7            solteiro   1o Grau       0     6.86    41      0  interior
32             casado   2o Grau       1    16.61    36      4  interior
30             casado   2o Grau       2    15.99    35     10   capital
29             casado   2o Grau       5    14.71    40      6  interior
28             casado   2o Grau       0    14.69    29      8  interior
26             casado   2o Grau       2    13.60    35      0     outro
25             casado   2o Grau       2    13.23    32      5  interior
21             casado   2o Grau       1    11.06    30      9     outro
22           solteiro   2o Grau       0    11.59    34      2   capital
35             casado   2o Grau       2    19.40    48     11   capital
17             casado   2o Grau       1     9.77    31      7   capital
16           solteiro   2o Grau       0     9.35    38      8     outro
15             casado   2o Grau       0     9.13    30      5  interior
4            solteiro   2o Grau       0     5.73    20     10     outro
13           solteiro   2o Grau       0     8.74    37      5     outro
11             casado   2o Grau       2     8.12    33      6  interior
10           solteiro   2o Grau       0     7.44    23      6     outro
9              casado   2o Grau       1     7.59    34     10   capital
20           solteiro   2o Grau       0    10.76    37      4  interior
19           solteiro  Superior       0    10.53    25      8  interior
24             casado  Superior       0    12.79    26      1     outro
31           solteiro  Superior       0    16.22    31      5     outro
33             casado  Superior       3    17.26    43      7   capital
34           solteiro  Superior       0    18.75    33      7   capital
36             casado  Superior       3    23.30    42      2  interior



---

- Criando a nova variável 'Idade' a partir de anos e meses

In [40]:
empresa_df['Idade'] = empresa_df['Anos'] + (empresa_df['Meses'] / 12)

In [41]:
empresa_df.head()

,Est.civil,Inst,Filhos,Salario,Anos,Meses,Regiao,Idade
Funcionario,,,,,,,,
1,solteiro,1o Grau,0,4.00,26,3,interior,26.250000
2,casado,1o Grau,1,4.56,32,10,capital,32.833333
3,casado,1o Grau,2,5.25,36,5,capital,36.416667
4,solteiro,2o Grau,0,5.73,20,10,outro,20.833333
5,solteiro,1o Grau,0,6.26,40,7,outro,40.583333



---

- Passando todos o textos para letras minúsculas

In [46]:
empresa_df['Inst'] = empresa_df['Inst'].str.lower()

In [47]:
empresa_df.head()

,Est.civil,Inst,Filhos,Salario,Anos,Meses,Regiao,Idade
Funcionario,,,,,,,,
1,solteiro,1o grau,0,4.00,26,3,interior,26.250000
2,casado,1o grau,1,4.56,32,10,capital,32.833333
3,casado,1o grau,2,5.25,36,5,capital,36.416667
4,solteiro,2o grau,0,5.73,20,10,outro,20.833333
5,solteiro,1o grau,0,6.26,40,7,outro,40.583333

In [57]:
hotel_df['Name'] = hotel_df['Name'].str.lower()
hotel_df['Place'] = hotel_df['Place'].str.lower()
hotel_df['Type'] = hotel_df['Type'].str.lower()
hotel_df['City'] = hotel_df['City'].str.lower()
hotel_df['State'] = hotel_df['State'].str.lower()

In [58]:
hotel_df.head()

,Name,Place,Type,Price_EUR,ReviewsCount,Rating,City,State
Hotel_ID,,,,,,,,
0,bunk hotel amsterdam,"amsterdam noord, amsterdam",bunk pod for 2,7887.0,778,8.4,amsterdam noord,amsterdam
1,yotel amsterdam,"amsterdam noord, amsterdam",premium double room,15267.0,500,8.1,amsterdam noord,amsterdam
2,multatuli hotel,"amsterdam city center, amsterdam",double room,13063.0,1605,7.4,amsterdam city center,amsterdam
3,nhow amsterdam rai,"zuideramstel, amsterdam",nhow double or twin room with view,12854.0,500,9.0,zuideramstel,amsterdam
4,motel one amsterdam,"zuideramstel, amsterdam",double room,9471.0,500,8.8,zuideramstel,amsterdam