In [2]:
people = {
    "first": ["Corey", 'Jane', 'John'],
    "last": ["Schafer", "Doe", "Doe"],
    "email": ["CoreyMSchafer@gmail.com", "JaneDoe@gmail.com", "JohnDoe@gmail.com"]
}

In [3]:
import pandas as pd

In [4]:
df = pd.DataFrame(people)

In [5]:
df

   first     last                    email
0  Corey  Schafer  CoreyMSchafer@gmail.com
1   Jane      Doe        JaneDoe@gmail.com
2   John      Doe        JohnDoe@gmail.com

In [6]:
df.columns

Index(['first', 'last', 'email'], dtype='str')

In [7]:
df.columns = ['first_name', 'last_name', 'email']

In [8]:
df

  first_name last_name                    email
0      Corey   Schafer  CoreyMSchafer@gmail.com
1       Jane       Doe        JaneDoe@gmail.com
2       John       Doe        JohnDoe@gmail.com

In [9]:
df.columns = [x.upper() for x in df.columns]
# this is a list comprehension that loops through each column name and applies the upper() method to it
df

  FIRST_NAME LAST_NAME                    EMAIL
0      Corey   Schafer  CoreyMSchafer@gmail.com
1       Jane       Doe        JaneDoe@gmail.com
2       John       Doe        JohnDoe@gmail.com

In [10]:
df.columns = df.columns.str.replace(' ', '_')
# replace any spaces with underscores in the column names
df

  FIRST_NAME LAST_NAME                    EMAIL
0      Corey   Schafer  CoreyMSchafer@gmail.com
1       Jane       Doe        JaneDoe@gmail.com
2       John       Doe        JohnDoe@gmail.com

In [11]:
df.columns = [x.lower() for x in df.columns]
df

  first_name last_name                    email
0      Corey   Schafer  CoreyMSchafer@gmail.com
1       Jane       Doe        JaneDoe@gmail.com
2       John       Doe        JohnDoe@gmail.com

In [12]:
df.rename(columns={'first_name': 'first', 'last_name': 'last'}, inplace=True)
# this will rename only the columns specified in the dictionary, and leave the rest of the columns unchanged
df

   first     last                    email
0  Corey  Schafer  CoreyMSchafer@gmail.com
1   Jane      Doe        JaneDoe@gmail.com
2   John      Doe        JohnDoe@gmail.com

In [13]:
df.loc[2] = ['John', 'Smith', 'JohnSmith@email.com']
df

   first     last                    email
0  Corey  Schafer  CoreyMSchafer@gmail.com
1   Jane      Doe        JaneDoe@gmail.com
2   John    Smith      JohnSmith@email.com

In [14]:
df.loc[2, ['last', 'email']] = ['Doe', 'JohnDoe@email.com']
df

   first     last                    email
0  Corey  Schafer  CoreyMSchafer@gmail.com
1   Jane      Doe        JaneDoe@gmail.com
2   John      Doe        JohnDoe@email.com

In [15]:
df.loc[2, 'last'] = 'Smith'
df

   first     last                    email
0  Corey  Schafer  CoreyMSchafer@gmail.com
1   Jane      Doe        JaneDoe@gmail.com
2   John    Smith        JohnDoe@email.com

In [16]:
df.at[2, 'last'] = 'Doe'
df

   first     last                    email
0  Corey  Schafer  CoreyMSchafer@gmail.com
1   Jane      Doe        JaneDoe@gmail.com
2   John      Doe        JohnDoe@email.com

In [22]:
# common mistakes when people try to change a single value without indexers
filt = (df['email'] == 'JohnDoe@email.com')
df[filt]['last'] = 'Smith'  # this will not work, it will give a SettingWithCopyWarning

/tmp/ipykernel_4742/936977475.py:3: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment.
Such chained assignment never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

Try using '.loc[row_indexer, col_indexer] = value' instead, to perform the assignment in a single step.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html#chained-assignment
  df[filt]['last'] = 'Smith'  # this will not work, it will give a SettingWithCopyWarning

In [18]:
df

   first     last                    email
0  Corey  Schafer  CoreyMSchafer@gmail.com
1   Jane      Doe        JaneDoe@gmail.com
2   John      Doe        JohnDoe@email.com

In [19]:
# this is the correct way to do it
filt = (df['email'] == 'JohnDoe@email.com')
df.loc[filt, 'last'] = 'Smith'
df

   first     last                    email
0  Corey  Schafer  CoreyMSchafer@gmail.com
1   Jane      Doe        JaneDoe@gmail.com
2   John    Smith        JohnDoe@email.com

-- Examples of how to update multiple rows of data

In [20]:
df['email'] = df['email'].str.lower()
df

   first     last                    email
0  Corey  Schafer  coreymschafer@gmail.com
1   Jane      Doe        janedoe@gmail.com
2   John    Smith        johndoe@email.com

-- More advanced way that we can update multiple rows of data

4 popular methods:

1. apply
2. map
3. applymap
4. replace

In [23]:
# apply
# can work with either a dataframe or a series object, and it can be used to apply a function to each element in a series or each series of a dataframe
df['email'].apply(len)  # this will return a series with the length of each email address

0    23
1    17
2    17
Name: email, dtype: int64

In [25]:
def update_email(email):
    return email.upper()

In [26]:
df['email'].apply(update_email)  # this will return a series with the email addresses in uppercase

0    COREYMSCHAFER@GMAIL.COM
1          JANEDOE@GMAIL.COM
2          JOHNDOE@EMAIL.COM
Name: email, dtype: str

In [27]:
df['email'] = df['email'].apply(update_email)
df

   first     last                    email
0  Corey  Schafer  COREYMSCHAFER@GMAIL.COM
1   Jane      Doe        JANEDOE@GMAIL.COM
2   John    Smith        JOHNDOE@EMAIL.COM

Lambda functions are basically anonymous functions with or without a specific name

In [29]:
df['email'] = df['email'].apply(lambda x: x.lower())
df

   first     last                    email
0  Corey  Schafer  coreymschafer@gmail.com
1   Jane      Doe        janedoe@gmail.com
2   John    Smith        johndoe@email.com

In [30]:
# using apply with a dataframe
df['email'].apply(len)

0    23
1    17
2    17
Name: email, dtype: int64

In [31]:
df.apply(len)
# this will return the number of rows in each column

first    3
last     3
email    3
dtype: int64

In [32]:
len(df['email'])  # this will return the number of rows in the email column

3

In [33]:
df.apply(len, axis='columns')  # this will return the number of columns in each row

0    3
1    3
2    3
dtype: int64

In [34]:
df.apply(pd.Series.min)  # this will return the minimum value (in alphabetical order) in each column

first                      Corey
last                         Doe
email    coreymschafer@gmail.com
dtype: str

In [37]:
df.apply(lambda x: x.min()) # this will give us the same result as the previous example

first                      Corey
last                         Doe
email    coreymschafer@gmail.com
dtype: str

In [ ]:
# this is map, applymap doesn't work
df.map(len)

   first  last  email
0      5     7     23
1      4     3     17
2      4     5     17

In [49]:
df.map(str.lower)

   first     last                    email
0  corey  schafer  coreymschafer@gmail.com
1   jane      doe        janedoe@gmail.com
2   john    smith        johndoe@email.com

In [ ]:
df['first'].map({'Corey': 'Chris', 'Jane': 'Mary'})  # this will return a series with the first names replaced according to the dictionary
# this will replace the name 'John' with NaN because it is not in the dictionary

0    Chris
1     Mary
2      NaN
Name: first, dtype: str

In [55]:
# replace method
df['first'].replace({'Corey': 'Chris', 'Jane': 'Mary'})
# using replace doesn't keeps the name 'John'

0    Chris
1     Mary
2     John
Name: first, dtype: str

In [56]:
df['first'] = df['first'].replace({'Corey': 'Chris', 'Jane': 'Mary'})
df

   first     last                    email
0  Chris  Schafer  coreymschafer@gmail.com
1   Mary      Doe        janedoe@gmail.com
2   John    Smith        johndoe@email.com